# Generated by Django 6.0 on 2026-03-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='hello@jesresstudio.com', max_length=254)),
                ('phone', models.CharField(default='+233 XX XXX XXXX', max_length=30)),
                ('location', models.CharField(default='Accra, Ghana', max_length=100)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(help_text='e.g. Instagram, Facebook, TikTok, YouTube', max_length=50)),
                ('handle', models.CharField(help_text='Display text e.g. @jesresstudio', max_length=100)),
                ('url', models.URLField(help_text='Full URL to the social media page')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower number appears first')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Social Link',
                'verbose_name_plural': 'Social Links',
                'ordering': ['order', 'platform'],
            },
        ),
    ]
