# Generated by Django 6.0 on 2026-03-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='tagline',
            field=models.TextField(default='Premium skin and makeup artistry by Maame Ama. Crafted for those who demand the finest.'),
        ),
    ]
