# Generated by Django 6.0 on 2026-03-23 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_tagline_to_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_bg',
            field=models.ImageField(blank=True, help_text='Full-screen hero section background image', null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='studio_bg',
            field=models.ImageField(blank=True, help_text='The Studio section background image (will be blurred)', null=True, upload_to='site/'),
        ),
    ]
