# Generated by Django 6.0 on 2026-03-23 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings_hero_bg_sitesettings_studio_bg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, help_text='e.g. Accra, Ghana', max_length=100)),
                ('comment', models.TextField()),
                ('profile_picture', models.ImageField(blank=True, help_text='Client photo or finished makeup shot', null=True, upload_to='testimonials/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower number appears first')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
