# Generated by Django 6.0 on 2026-03-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntroVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('jesoco', 'JES.CO Homepage'), ('studio', 'Jesres Glam Studio')], help_text='Which page this video appears on', max_length=20, unique=True)),
                ('video_file', models.FileField(help_text='Upload MP4 video file', upload_to='videos/')),
                ('title', models.CharField(blank=True, help_text='Optional caption shown below the video', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide the video without deleting it')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Intro Video',
                'verbose_name_plural': 'Intro Videos',
            },
        ),
    ]
