# Generated by Django 6.0 on 2026-03-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_introvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='testimonials_bg',
            field=models.ImageField(blank=True, help_text='Testimonials section background image', null=True, upload_to='site/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='studio_bg',
            field=models.ImageField(blank=True, help_text='The Studio section background image', null=True, upload_to='site/'),
        ),
    ]
