# Generated by Django 6.0 on 2026-06-11 15:17

import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sitesettings_testimonials_bg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_hero', imagekit.models.fields.ProcessedImageField(blank=True, help_text='Full-screen background photo on the JES.CO home page hero.', null=True, upload_to='site/home/')),
                ('home_studio_feature', imagekit.models.fields.ProcessedImageField(blank=True, help_text='Photo shown in the "Studio" feature section on the home page.', null=True, upload_to='site/home/')),
                ('studio_portrait', imagekit.models.fields.ProcessedImageField(blank=True, help_text="Maame Ama's portrait shown in the studio page hero (arch frame).", null=True, upload_to='site/studio/')),
                ('studio_about', imagekit.models.fields.ProcessedImageField(blank=True, help_text='Photo shown in the "About the Studio" section.', null=True, upload_to='site/studio/')),
                ('studio_booking', imagekit.models.fields.ProcessedImageField(blank=True, help_text='Atmosphere photo shown beside the booking form.', null=True, upload_to='site/studio/')),
                ('studio_testimonials_bg', imagekit.models.fields.ProcessedImageField(blank=True, help_text='Subtle background photo behind the testimonials section.', null=True, upload_to='site/studio/')),
            ],
            options={
                'verbose_name': 'Page Images',
                'verbose_name_plural': 'Page Images',
            },
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='hero_bg',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='studio_bg',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='testimonials_bg',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5, help_text='Star rating out of 5'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='service',
            field=models.CharField(blank=True, help_text='e.g. Bridal Glam, Editorial', max_length=100),
        ),
        migrations.AlterField(
            model_name='introvideo',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to hide without deleting'),
        ),
        migrations.AlterField(
            model_name='introvideo',
            name='title',
            field=models.CharField(blank=True, help_text='Optional caption', max_length=200),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='platform',
            field=models.CharField(help_text='e.g. Instagram, TikTok, YouTube', max_length=50),
        ),
    ]
