# Generated by Django 6.0 on 2026-06-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_pageimages_remove_sitesettings_hero_bg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='introvideo',
            name='video_file',
        ),
        migrations.AddField(
            model_name='introvideo',
            name='video_url',
            field=models.URLField(blank=True, help_text='[Cloudinary] Paste Cloudinary video URL'),
        ),
        migrations.AlterField(
            model_name='pageimages',
            name='home_hero',
            field=models.URLField(blank=True, help_text='[R2] Full-screen background photo on the JES.CO home page hero.', null=True),
        ),
        migrations.AlterField(
            model_name='pageimages',
            name='home_studio_feature',
            field=models.URLField(blank=True, help_text='[R2] Photo shown in the "Studio" feature section on the home page.', null=True),
        ),
        migrations.AlterField(
            model_name='pageimages',
            name='studio_about',
            field=models.URLField(blank=True, help_text='[R2] Photo shown in the "About the Studio" section.', null=True),
        ),
        migrations.AlterField(
            model_name='pageimages',
            name='studio_booking',
            field=models.URLField(blank=True, help_text='[R2] Atmosphere photo shown beside the booking form.', null=True),
        ),
        migrations.AlterField(
            model_name='pageimages',
            name='studio_portrait',
            field=models.URLField(blank=True, help_text="[R2] Maame Ama's portrait shown in the studio page hero (arch frame).", null=True),
        ),
        migrations.AlterField(
            model_name='pageimages',
            name='studio_testimonials_bg',
            field=models.URLField(blank=True, help_text='[R2] Subtle background photo behind the testimonials section.', null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='profile_picture',
            field=models.URLField(blank=True, help_text='[R2] Paste Cloudflare R2 URL for client photo or finished makeup shot.', null=True),
        ),
    ]
