# Generated by Django 6.0 on 2026-06-13 13:14

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_introvideo_video_file_introvideo_video_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageimages',
            name='home_hero',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Full-screen background photo on the JES.CO home page hero.', null=True, upload_to='pages/'),
        ),
        migrations.AlterField(
            model_name='pageimages',
            name='home_studio_feature',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Photo shown in the "Studio" feature section on the home page.', null=True, upload_to='pages/'),
        ),
        migrations.AlterField(
            model_name='pageimages',
            name='studio_about',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Photo shown in the "About the Studio" section.', null=True, upload_to='pages/'),
        ),
        migrations.AlterField(
            model_name='pageimages',
            name='studio_booking',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Atmosphere photo shown beside the booking form.', null=True, upload_to='pages/'),
        ),
        migrations.AlterField(
            model_name='pageimages',
            name='studio_portrait',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text="Maame Ama's portrait shown in the studio page hero (arch frame).", null=True, upload_to='pages/'),
        ),
        migrations.AlterField(
            model_name='pageimages',
            name='studio_testimonials_bg',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Subtle background photo behind the testimonials section.', null=True, upload_to='pages/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='profile_picture',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Client photo or finished makeup shot.', null=True, upload_to='testimonials/'),
        ),
    ]
