# Generated by Django 6.0 on 2026-06-13 15:26

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_pageimages_home_hero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introvideo',
            name='video_url',
            field=models.FileField(blank=True, help_text='Upload intro video (MP4). Goes to Cloudinary in production.', null=True, storage=core.models._video_storage, upload_to='intro_videos/'),
        ),
    ]
