# Generated by Django 6.0 on 2026-07-01 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_introvideo_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='platform',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('facebook', 'Facebook'), ('x', 'X (Twitter)'), ('pinterest', 'Pinterest'), ('snapchat', 'Snapchat'), ('threads', 'Threads'), ('linkedin', 'LinkedIn'), ('whatsapp', 'WhatsApp')], help_text='Select the social media platform', max_length=50),
        ),
    ]
