# Generated by Django 6.0 on 2026-07-10 02:12

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_sociallink_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introvideo',
            name='video_url',
            field=models.FileField(blank=True, help_text='Upload intro video (MP4). Streams via Bunny Stream (HLS).', null=True, storage=core.models._video_storage, upload_to='intro_videos/'),
        ),
    ]
