# Generated by Django 6.0

import django.db.models.deletion
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_introvideo_video_url'),
        ('courses', '0009_coursepurchase_expiry_notice_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='testimonial_type',
            field=models.CharField(choices=[('client', 'Client'), ('student', 'Student')], default='client', help_text='Client = studio/beauty service. Student = course.', max_length=20),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='before_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Optional — shown as a before/after slider on the full testimonials page.', null=True, upload_to='testimonials/before/'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='after_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Optional — pair with Before Image above.', null=True, upload_to='testimonials/after/'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='source_comment',
            field=models.ForeignKey(blank=True, help_text='Set automatically when promoted from a course comment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_testimonials', to='courses.coursecomment'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='service',
            field=models.CharField(blank=True, help_text='e.g. Bridal Glam, Editorial, or the course title', max_length=100),
        ),
    ]
