# Generated by Django 6.0

import django.utils.timezone
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_testimonial_before_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, help_text='GHS amount earned from this booking.', max_digits=10)),
                ('description', models.CharField(blank=True, help_text='e.g. "Bridal glam — Ama K."', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Booking Revenue',
                'verbose_name_plural': 'Booking Revenue',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='announcements/')),
                ('start_date', models.DateField(help_text='First day this event/workshop is happening (or the only day, for single-day events).')),
                ('end_date', models.DateField(blank=True, help_text='Last day, for multi-day events. Leave blank for single-day events.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Untick to pull this down without deleting it.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower number appears first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-start_date'],
            },
        ),
    ]
