# Generated by Django 6.0 on 2026-03-22 14:32

import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('hair', 'Hair'), ('makeup', 'Makeup'), ('nails', 'Nails'), ('skin', 'Skin / Glow'), ('lashes', 'Lashes'), ('brows', 'Brows')], max_length=20)),
                ('before_image', imagekit.models.fields.ProcessedImageField(upload_to='gallery/before/')),
                ('after_image', imagekit.models.fields.ProcessedImageField(upload_to='gallery/after/')),
                ('is_published', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower number appears first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gallery Item',
                'verbose_name_plural': 'Gallery Items',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
