# Generated by Django 6.0 on 2026-03-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryitem',
            name='is_published',
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='publish_at',
            field=models.DateTimeField(blank=True, help_text='Leave blank to save as draft. Set to now or a future time to schedule.', null=True),
        ),
    ]
