# Generated by Django 6.0 on 2026-07-23 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkinAnalysisSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('skin_tone', models.CharField(choices=[('fair', 'Fair'), ('light', 'Light'), ('medium', 'Medium'), ('tan', 'Tan'), ('deep', 'Deep'), ('very_deep', 'Very Deep')], max_length=20)),
                ('undertone', models.CharField(choices=[('warm', 'Warm'), ('cool', 'Cool'), ('neutral', 'Neutral'), ('not_sure', 'Not sure')], max_length=20)),
                ('skin_type', models.CharField(choices=[('oily', 'Oily'), ('dry', 'Dry'), ('combination', 'Combination'), ('normal', 'Normal'), ('sensitive', 'Sensitive')], max_length=20)),
                ('skin_concern', models.CharField(choices=[('acne', 'Acne/breakouts'), ('hyperpigmentation', 'Hyperpigmentation'), ('dryness', 'Dryness'), ('aging', 'Fine lines/aging'), ('uneven_texture', 'Uneven texture'), ('other', 'Other')], max_length=20)),
                ('allergies', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('allergies_detail', models.CharField(blank=True, help_text='Only used if allergies = Yes', max_length=300)),
                ('makeup_routine', models.CharField(choices=[('full_glam', 'Full glam'), ('natural_everyday', 'Natural everyday'), ('special_occasions', 'Special occasions only'), ('none', "Don't wear makeup")], max_length=20)),
                ('foundation_finish', models.CharField(choices=[('matte', 'Matte'), ('dewy', 'Dewy'), ('natural_satin', 'Natural-satin'), ('not_sure', 'Not sure')], max_length=20)),
                ('occasion', models.CharField(choices=[('everyday', 'Everyday wear'), ('bridal', 'Bridal'), ('photoshoot', 'Photoshoot/editorial'), ('event', 'Event/party'), ('skincare_routine', 'General skincare routine')], max_length=20)),
                ('budget', models.CharField(choices=[('budget_friendly', 'Budget-friendly'), ('mid_range', 'Mid-range'), ('luxury', 'Luxury'), ('no_preference', 'No preference')], max_length=20)),
                ('additional_notes', models.TextField(blank=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('paystack_reference', models.CharField(blank=True, max_length=100)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('replied', models.BooleanField(default=False, help_text="Tick once you've personally emailed this customer your recommendation.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Skin Analysis Submission',
                'verbose_name_plural': 'Skin Analysis Submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
