# Generated by Django 6.0 on 2026-07-23 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skinanalysissubmission',
            name='additional_notes',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
