# Generated by Django 6.0 on 2026-04-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_magiclinktoken_usersession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magiclinktoken',
            name='token',
            field=models.CharField(max_length=96, unique=True),
        ),
    ]
