# Generated by Django 6.0 on 2026-04-13 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_magiclinktoken_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscription_tier',
        ),
    ]
