# Generated by Django 6.0 on 2026-06-13 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_expiry_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersession',
            name='token',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='user',
        ),
        migrations.DeleteModel(
            name='MagicLinkToken',
        ),
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
