# Generated by Django 6.0 on 2026-03-28 18:24

import django.db.models.deletion
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_bg', models.ImageField(blank=True, help_text='Courses page hero background image', null=True, upload_to='courses/')),
                ('hero_heading', models.CharField(default='Master the Art of Beauty', max_length=200)),
                ('hero_subtext', models.TextField(default='Step-by-step video courses taught by Maame Ama — learn professional makeup at your own pace.')),
            ],
            options={
                'verbose_name': 'Course Page Settings',
                'verbose_name_plural': 'Course Page Settings',
            },
        ),
        migrations.CreateModel(
            name='CourseTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Basic, Silver, Gold', max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('badge_color', models.CharField(default='#D4AF37', help_text='Hex colour for the tier badge, e.g. #D4AF37', max_length=20)),
                ('price_display', models.CharField(blank=True, help_text='Display price shown on cards, e.g. GHS 250', max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower number appears first')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Course Tier',
                'verbose_name_plural': 'Course Tiers',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField()),
                ('what_youll_learn', models.TextField(blank=True, help_text='One point per line — shown as a bullet list')),
                ('thumbnail', imagekit.models.fields.ProcessedImageField(help_text='Course cover image — auto-converted to WebP', upload_to='courses/thumbnails/')),
                ('category', models.CharField(choices=[('foundation', 'Foundation & Base'), ('eyes', 'Eye Artistry'), ('contour', 'Contouring & Sculpting'), ('bridal', 'Bridal Makeup'), ('full_glam', 'Full Glam'), ('editorial', 'Editorial / Creative'), ('lips', 'Lip Artistry'), ('color_theory', 'Color Theory')], max_length=20)),
                ('trailer_video', models.FileField(help_text='Short trailer — visible to everyone, no login required', upload_to='courses/trailers/')),
                ('course_video', models.FileField(help_text='Full course video — locked behind the tier paywall', upload_to='courses/videos/')),
                ('duration_display', models.CharField(blank=True, help_text='e.g. 3h 20m — shown on the course card', max_length=30)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on the studio homepage preview (max 3)')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide without deleting')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower number appears first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tier', models.ForeignKey(help_text='Which tier unlocks this course', on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='courses.coursetier')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
