# Generated by Django 6.0 on 2026-06-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='subtitle_url',
            field=models.URLField(blank=True, help_text='[Cloudinary] Paste Cloudinary .vtt subtitle file URL (optional).'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_video',
            field=models.URLField(blank=True, help_text='[Cloudinary] Paste Cloudinary URL for the full tier-locked course video.'),
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.URLField(blank=True, help_text='[R2] Paste Cloudflare R2 URL for the course cover image.'),
        ),
        migrations.AlterField(
            model_name='course',
            name='trailer_video',
            field=models.URLField(blank=True, help_text='[Cloudinary] Paste Cloudinary URL for the short public trailer video.'),
        ),
        migrations.AlterField(
            model_name='coursepagesettings',
            name='hero_bg',
            field=models.URLField(blank=True, help_text='[R2] Paste Cloudflare R2 URL for the courses page hero background image.', null=True),
        ),
    ]
