# Generated by Django 6.0 on 2026-06-12 08:16

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_video',
            field=models.FileField(help_text='Full course video — locked behind the tier paywall. MP4/MOV/WEBM only.', upload_to='courses/videos/', validators=[courses.models.validate_video_file]),
        ),
        migrations.AlterField(
            model_name='course',
            name='trailer_video',
            field=models.FileField(help_text='Short trailer — visible to everyone, no login required. MP4/MOV/WEBM only.', upload_to='courses/trailers/', validators=[courses.models.validate_video_file]),
        ),
    ]
