# Generated by Django 6.0 on 2026-06-13 13:14

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_subtitle_url_alter_course_course_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Course cover image.', null=True, upload_to='courses/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='coursepagesettings',
            name='hero_bg',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Courses page hero background image.', null=True, upload_to='courses/heroes/'),
        ),
    ]
