# Generated by Django 6.0 on 2026-06-13 14:34

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_video',
            field=models.FileField(blank=True, help_text='Upload the full tier-locked course video (MP4). Goes to Cloudinary in production.', null=True, storage=courses.models._video_storage, upload_to='courses/videos/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='trailer_video',
            field=models.FileField(blank=True, help_text='Upload the short public trailer video (MP4). Goes to Cloudinary in production.', null=True, storage=courses.models._video_storage, upload_to='courses/trailers/'),
        ),
    ]
