# Generated by Django 6.0 on 2026-06-13 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_course_video_alter_course_trailer_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('token', models.CharField(max_length=96, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Course Access Token',
                'verbose_name_plural': 'Course Access Tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('session_key', models.CharField(max_length=96, unique=True)),
                ('device_hint', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Course Session',
                'verbose_name_plural': 'Course Sessions',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(default=0, help_text='Price in Ghana Cedis (GHS). Used for Paystack checkout.'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tier',
            field=models.ForeignKey(help_text='Display tier label only — Basic, Premium, Exclusive etc.', on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='courses.coursetier'),
        ),
        migrations.CreateModel(
            name='CourseComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False, help_text='Tick to make this comment visible on the site.')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='courses.course')),
            ],
            options={
                'verbose_name': 'Course Comment',
                'verbose_name_plural': 'Course Comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoursePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('paystack_reference', models.CharField(blank=True, help_text='Paystack transaction reference — auto-filled by webhook.', max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='courses.course')),
            ],
            options={
                'verbose_name': 'Course Purchase',
                'verbose_name_plural': 'Course Purchases',
                'ordering': ['-purchased_at'],
                'unique_together': {('email', 'course')},
            },
        ),
        migrations.CreateModel(
            name='VideoHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=96)),
                ('ip_address', models.GenericIPAddressField()),
                ('last_ping', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heartbeats', to='courses.course')),
            ],
            options={
                'verbose_name': 'Video Heartbeat',
                'verbose_name_plural': 'Video Heartbeats',
                'unique_together': {('session_key', 'course')},
            },
        ),
    ]
