# Generated by Django 6.0 on 2026-06-20 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_courseaccesstoken_coursesession_course_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('courses.coursepurchase',),
        ),
    ]
