# Generated by Django 6.0 on 2026-06-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_add_student_proxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepurchase',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Access expiry date. Auto-set to 6 months from purchase. Edit to extend.', null=True),
        ),
    ]
