# Generated by Django 6.0 on 2026-07-10 02:12

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_add_purchase_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_video',
            field=models.FileField(blank=True, help_text='Upload the full tier-locked course video (MP4). Streams via Bunny Stream (HLS).', null=True, storage=courses.models._video_storage, upload_to='courses/videos/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='subtitle_url',
            field=models.URLField(blank=True, help_text='Paste the .vtt subtitle file URL (optional).'),
        ),
        migrations.AlterField(
            model_name='course',
            name='trailer_video',
            field=models.FileField(blank=True, help_text='Upload the short public trailer video (MP4). Streams via Bunny Stream (HLS).', null=True, storage=courses.models._video_storage, upload_to='courses/trailers/'),
        ),
    ]
