# Generated by Django 6.0 on 2026-07-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_course_course_video_alter_course_subtitle_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepurchase',
            name='expiry_notice_sent',
            field=models.BooleanField(default=False, help_text='Access-expired notice email sent.'),
        ),
        migrations.AddField(
            model_name='coursepurchase',
            name='reminder_14_sent',
            field=models.BooleanField(default=False, help_text='14-day expiry reminder email sent.'),
        ),
        migrations.AddField(
            model_name='coursepurchase',
            name='reminder_5_sent',
            field=models.BooleanField(default=False, help_text='5-day expiry reminder email sent.'),
        ),
    ]
