# Generated by Django 6.0

from django.db import migrations, models


def backfill_price_paid(apps, schema_editor):
    """Snapshot each existing purchase's price from its course's current price (best available approximation)."""
    CoursePurchase = apps.get_model('courses', 'CoursePurchase')
    for purchase in CoursePurchase.objects.select_related('course').filter(price_paid__isnull=True):
        purchase.price_paid = purchase.course.price
        purchase.save(update_fields=['price_paid'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_coursepurchase_expiry_notice_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepurchase',
            name='price_paid',
            field=models.PositiveIntegerField(blank=True, help_text='GHS amount actually paid at time of purchase/renewal — snapshot so revenue stays accurate if the course price changes later.', null=True),
        ),
        migrations.RunPython(backfill_price_paid, noop),
    ]
