# Generated by Django 6.0

import courses.models
import django.core.validators
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_coursepurchase_price_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecomment',
            name='name',
            field=models.CharField(blank=True, help_text="Student's name — carried over if this comment is promoted to a testimonial.", max_length=150),
        ),
        migrations.AddField(
            model_name='coursecomment',
            name='before_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Optional — before photo for a full testimonial submission (max 5MB).', null=True, upload_to='testimonials/before/', validators=[courses.models.validate_image_size_5mb]),
        ),
        migrations.AddField(
            model_name='coursecomment',
            name='after_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Optional — pair with Before Image above (max 5MB).', null=True, upload_to='testimonials/after/', validators=[courses.models.validate_image_size_5mb]),
        ),
    ]
