# Generated by Django 6.0

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_coursecomment_testimonial_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursetier',
            name='price_display',
        ),
    ]
