# Generated by Django 6.0.8 on 2026-08-25 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_remove_coursetier_price_display'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedPaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, max_length=100, unique=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Processed Payment Event',
                'verbose_name_plural': 'Processed Payment Events',
            },
        ),
    ]
