# Generated by Django 6.0.8 on 2026-08-25 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_processedpaymentevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecomment',
            name='name',
            field=models.CharField(blank=True, help_text='Public nickname the student chooses when leaving a review — shown publicly if approved and promoted to a testimonial. Never their real name or email.', max_length=150),
        ),
    ]
