# Generated by Django 6.0 on 2026-03-28 14:35

import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.CharField(blank=True, help_text='e.g. GHS 150 or GHS 80 – 120', max_length=50)),
                ('image', imagekit.models.fields.ProcessedImageField(help_text='Product photo — will be auto-converted to WebP', upload_to='products/')),
                ('category', models.CharField(choices=[('makeup', 'Makeup Sets'), ('skincare', 'Skincare Sets'), ('collections', 'Curated Collections')], max_length=20)),
                ('stock_status', models.CharField(choices=[('in_stock', 'In Stock'), ('out_of_stock', 'Out of Stock'), ('coming_soon', 'Coming Soon')], default='in_stock', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower number appears first')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide from the website without deleting')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Product Item',
                'verbose_name_plural': 'Product Items',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
