# Generated by Django 6.0 on 2026-06-20 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('ghana', 'Ghana'), ('usa', 'USA')], max_length=10)),
                ('location_name', models.CharField(help_text='e.g. Accra, Kumasi, New York', max_length=200)),
                ('price', models.DecimalField(decimal_places=2, help_text='Delivery fee in GHS (Ghana) or USD (USA)', max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower number appears first')),
            ],
            options={
                'verbose_name': 'Delivery Zone',
                'verbose_name_plural': 'Delivery Zones',
                'ordering': ['country', 'order', 'location_name'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='order',
            name='paystack_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='products.deliveryzone'),
        ),
    ]
