# Generated by Django 6.0

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_deliveryzone_order_delivery_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0, help_text='Units in stock. Auto-syncs Stock Status below — flips to Out of Stock at 0.'),
        ),
        migrations.AddField(
            model_name='order',
            name='amount_ghs',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Real numeric amount charged via Paystack. Null for WhatsApp/manual orders.', max_digits=10, null=True),
        ),
    ]
