# Generated by Django 6.0

import re

from django.db import migrations

# Confirmed/webhook-created orders always store total as f'{currency} {amount_ghs:.2f}'
# (never a range — ranges only ever occur in ProductItem.price), so this is a reliable parse.
_TOTAL_RE = re.compile(r'^[A-Za-z]+\s+([\d.]+)$')


def backfill_amount_ghs(apps, schema_editor):
    Order = apps.get_model('products', 'Order')
    for order in Order.objects.filter(status='confirmed', amount_ghs__isnull=True):
        match = _TOTAL_RE.match((order.total or '').strip())
        if match:
            order.amount_ghs = match.group(1)
            order.save(update_fields=['amount_ghs'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productitem_quantity_order_amount_ghs'),
    ]

    operations = [
        migrations.RunPython(backfill_amount_ghs, noop),
    ]
