# Generated by Django 6.0

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_backfill_order_amount_ghs'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='price_usd',
            field=models.CharField(blank=True, help_text='e.g. USD 45 or USD 25 – 40. Shown to USA-region visitors instead of the GHS price above. Leave blank to fall back to the GHS price.', max_length=50),
        ),
    ]
