# Generated by Django 6.0

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productitem_price_finalize'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='USD-equivalent total quoted at checkout for USA orders. Null for Ghana/WhatsApp orders.', max_digits=10, null=True),
        ),
    ]
