# Generated by Django 6.0.8 on 2026-08-25 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_order_amount_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_token',
            field=models.CharField(blank=True, help_text="Opaque token for the emailed order-tracking link — keeps the customer's email out of a URL that ends up in browser history and server logs. Auto-generated on creation.", max_length=96, null=True, unique=True),
        ),
    ]
